<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Common Language Lines
    |--------------------------------------------------------------------------
    */

    'generated_by' => 'Generated by Orion (https://github.com/fspnet/orion)',
];